# Generated by Django 3.1.6 on 2021-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210228_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
