# Generated by Django 3.1.6 on 2021-02-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210216_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pfp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
