# Generated by Django 3.1.6 on 2021-03-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210301_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number_of_listings',
        ),
    ]
